# Generated by Django 3.1.3 on 2020-11-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_remove_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='discogs',
            new_name='discogs_url',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='soundcloud',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=1050, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='resident_advisor_url',
            field=models.URLField(blank=True, max_length=1050, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud_embed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud_url',
            field=models.URLField(blank=True, max_length=1050, null=True),
        ),
    ]
