# Generated by Django 3.1.3 on 2020-11-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20201128_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='soundcloud_embed',
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=1050, null=True),
        ),
    ]
