# Generated by Django 3.1.3 on 2020-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_auto_20201128_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
