# Generated by Django 3.1.3 on 2020-11-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201118_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist_foreign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.artist'),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=300),
        ),
    ]
