# Generated by Django 3.1.3 on 2020-11-18 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201118_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='artist_foreign',
        ),
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.artist'),
        ),
    ]
