# Generated by Django 3.1.3 on 2020-11-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201118_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.artist'),
            preserve_default=False,
        ),
    ]
