# Generated by Django 3.1.3 on 2020-11-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20201123_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
